blank_issues_enabled: false
contact_links:
  - name: Foundry Discord Server Support Channel
    url: https://discord.com/channels/1044304864903168061/1076959517767651358
    about: Please use this if you need help.